categories = ['Anal', 'BDSM', 'Celebrities & Fan Fiction', 'Chain Stories', 'Erotic Couplings', 'Erotic Horror', 'Exhibitionist & Voyeur', 'Fetish', 'First Time', 'Gay Male', 'Group Sex', 'How To', 'Humor & Satire', 'Incest/Taboo', 'Interracial Love', 'Lesbian Sex', 'Letters & Transcripts', 'Loving Wives', 'Mature', 'Mind Control', 'Non-Erotic', 'NonConsent/Reluctance', 'NonHuman', 'Novels and Novellas', 'Reviews & Essays', 'Romance', 'Sci-Fi & Fantasy', 'Text with Audio', 'Toys & Masturbation', 'Transgender & Crossdressers Stories']
category_urls = {"Anal":"https://www.literotica.com/c/anal-sex-stories",
                 "BDSM":"https://www.literotica.com/c/bdsm-stories",
                 "Celebrities & Fan Fiction":"https://www.literotica.com/c/celebrity-stories",
                 "Chain Stories":"https://www.literotica.com/c/chain-stories",
                 "Erotic Couplings":"https://www.literotica.com/c/erotic-couplings",
                 "Erotic Horror":"https://www.literotica.com/c/erotic-horror",
                 "Exhibitionist & Voyeur": "https://www.literotica.com/c/exhibitionist-voyeur",
                 "Fetish":"https://www.literotica.com/c/fetish-stories",
                 "First Time":"https://www.literotica.com/c/first-time-sex-stories",
                 "Gay Male":"https://www.literotica.com/c/gay-sex-stories",
                 "Group Sex":"https://www.literotica.com/c/group-sex-stories",
                 "How To":"https://www.literotica.com/c/adult-how-to",
                 "Humor & Satire":"https://www.literotica.com/c/adult-humor",
#                 "Illustrated": "https://www.literotica.com/c/illustrated-erotic-fiction", Weird format.
                 "Incest/Taboo": "https://www.literotica.com/c/taboo-sex-stories",
                 "Interracial Love":"https://www.literotica.com/c/interracial-erotic-stories",
                 "Lesbian Sex":"https://www.literotica.com/c/lesbian-sex-stories",
                 "Letters & Transcripts":"https://www.literotica.com/c/erotic-letters",
                 "Loving Wives":"https://www.literotica.com/c/loving-wives",
                 "Mature":"https://www.literotica.com/c/mature-sex",
                 "Mind Control":"https://www.literotica.com/c/mind-control",
#                 "Non-English":"https://www.literotica.com/c/non-english-stories", Only one story
                 "Non-Erotic":"https://www.literotica.com/c/non-erotic-stories",
                 "NonConsent/Reluctance":"https://www.literotica.com/c/non-consent-stories",
                 "NonHuman":"https://www.literotica.com/c/non-human-stories",
                 "Novels and Novellas":"https://www.literotica.com/c/erotic-novels",
                 "Reviews & Essays":"https://www.literotica.com/c/reviews-and-essays",
                 "Romance":"https://www.literotica.com/c/adult-romance",
                 "Sci-Fi & Fantasy":"https://www.literotica.com/c/science-fiction-fantasy",
                 "Text with Audio":"https://www.literotica.com/c/audio-sex-stories",
                 "Toys & Masturbation":"https://www.literotica.com/c/masturbation-stories",
                 "Transgender & Crossdressers Stories":"https://www.literotica.com/c/transsexuals-crossdressers"
}
